// GENERATED BY DEMETRA
// DOES NOT EDIT

package characters

import "github.com/ihatiko/olymp/temple/transports/grpc"

const (
	sdkGrpcName = "Grpc Characters Service"
)

type CharactersConfig struct {
	grpc.Config
}

type CharactersServiceTransport struct {
	grpc.Transport
}

func (p *CharactersConfig) Use() CharactersServiceTransport {
	return CharactersServiceTransport{Transport: p.Config.Use()}
}

func (p *CharactersConfig) Name() string {
	return sdkGrpcName
}

func (t CharactersServiceTransport) Routing(impl CharactersServiceServer) CharactersServiceTransport {
	t.Transport.Routing(CharactersService_ServiceDesc, impl)
	return t
}
