[tech.service]
# имя сервиса
name = "example"
# режим дебага
debug = true

[daemon]
# таймаут на выполнение тикера
timeout = "30s"
# как часто вызывается тикер
interval = "1s"
# количество паралельный воркеров через горутины
workers = 1

[cron]
# таймаут на выполнение кроны
timeout = "30s"
# количество паралельный воркеров через горутины
workers = 1

[grpc]
port = ":8082"

[read-postgresql]
host="localhost"
port=5432
database="example"
user="postgres"
password="postgres"

[write-postgresql]
host="localhost"
port=5432
database="example"
user="postgres"
password="postgres"

