[tech.service]
# имя сервиса
name = "example"
# режим дебага
debug = true

[daemon]
# таймаут на выполнение тикера
timeout = "30s"
# как часто вызывается тикер
interval = "5s"
# количество паралельный воркеров через горутины
workers = 1

[cron]
# таймаут на выполнение кроны
timeout = "30s"
# количество паралельный воркеров через горутины
workers = 1

[grpc]
port = ":10001"

[read-postgresql]
host="localhost"
port=5432
database="example"
user="postgres"
password="postgres"

[write-postgresql]
host="localhost"
port=5432
database="example"
user="postgres"
password="postgres"

[redis]
addr = "localhost:6379"
db = 0
masterName = "mymaster"
sentinelAddrs = [":26379", ":26379", ":26379"]

[kafka]
brokers=["localhost:9092"]

[planets-producer]
topic="example.planets.create"