// GENERATED BY DEMETRA
// DOES NOT EDIT

package peoples

import "github.com/ihatiko/olymp/components/transports/grpc"

const (
	sdkGrpcName = "Grpc PlanetsService"
)

type PeoplesConfig struct {
	grpc.Config
}

type PeoplesTransport struct {
	grpc.Transport
}

func (p *PeoplesConfig) Use() PeoplesTransport {
	return PeoplesTransport{Transport: p.Config.Use()}
}

func (p *PeoplesConfig) Name() string {
	return sdkGrpcName
}

func (t PeoplesTransport) Routing(impl PeoplesServiceServer) PeoplesTransport {
	t.Transport.Routing(PeoplesService_ServiceDesc, impl)
	return t
}
