[tech.http]
Port = 8080
PprofPort = 8081
Pprof = true
LivenessPath = "/liveness"
ReadinessPath = "/readiness"
MetricsPath = "/metrics"

[tech.tracer]
host = "http://localhost:14268/api/traces"
ratio = 0.1

[tech.profiler]
host = "http://localhost:4040"
ratio = 5

[tech.log]
encoding = "json"
level = "info"
devMode = false