// GENERATED BY DEMETRA
// DOES NOT EDIT

package planets

import "github.com/ihatiko/olymp/temple/transports/grpc"

const (
	sdkGrpcName = "Grpc Planets Service"
)

type PlanetsConfig struct {
	grpc.Config
}

type PlanetsTransport struct {
	grpc.Transport
}

func (p *PlanetsConfig) Use() PlanetsTransport {
	return PlanetsTransport{Transport: p.Config.Use()}
}

func (p *PlanetsConfig) Name() string {
	return sdkGrpcName
}

func (t PlanetsTransport) Routing(impl PlanetsServiceServer) PlanetsTransport {
	t.Transport.Routing(PlanetsService_ServiceDesc, impl)
	return t
}
