[tech.service]
# имя сервиса
name = "example"
# режим дебага
debug = true

[tech.http]
port = 8080
pprof-port = 8081
pprof = true
liveness-path = "/liveness"
readiness-path = "/readiness"
metrics-path = "/metrics"

[tech.tracer]
host = "http://localhost:14268/api/traces"
ratio = 0.1

[tech.profiler]
host = "http://localhost:4040"
ratio = 5

[tech.log]
encoding = "json"
level = "info"